version: '3'
services:
  backend:
    build:
      context: .  # Build context should be the root of your project
      dockerfile: Dockerfile  # Path to Dockerfile for backend
    ports:
      - "5000:5000"
    env_file:
      - .env

