name: Test Pipeline

on:
  push:
    branches:
      - master # Replace with your default branch or other branches to monitor
  workflow_dispatch:  # Add this line to enable manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Display message
      run: echo "code pushed"
